package test.pokemongame;

public enum City {
    PALLET_TOWN,
    VIRIDIAN_CITY,
    PEWTER_CITY,
    CERULEAN_CITY,
    VERMILION_CITY,
    LAVENDER_TOWN,
    CELADON_CITY,
    FUCHSIA_CITY,
    SAFFRON_CITY,
    CINNABAR_ISLAND,
}